### ISSUE TITLE
BEFORE REBUILDING TO EXE KEEP TRACK OF UPDATES: once everything is done, rebuild and test > maybe make a new release

### ISSUE THREAD

**Issue by AccelQuasarDragon** [AccelQuasarDragon/FastCVApp#30]
- [x] BEFORE REBUILDING KEEP TRACK OF UPDATES
	- [x] remove source as arg 288
	- [x] made it work for pypi as a module
	- [x] fixed sanity checks
	- [x] made popup widget resize properly in Mac
	- [x] stopped bug where u can crash the app by setting time before cv functions are loaded
	- [x] removed visual bug on mac when double clicking made a red dot
	- [x] applied upx on windows builds (not applicable for mac as per pyinstaller https://pyinstaller.org/en/stable/usage.html#using-upx)
	- [x] uploading a new file automatically updates total time
	- [x] added try/except blocks so the app crashes gracefully when made in pyinstaller. it doesn't instantly exit. instead it says the error and waits 300 seconds before exiting if using confole= True.
	- [x] removed .gitignore from repo
	- [x] updated requirements.txt for windows and mac
	- [x] made working example project using fastcvapp as a pypi module
- [x] When you rebuild there are a lot of changes:
	- [x] BUILD IN CLEAN ENV AS PER #9 and #22
	- [x] no 1: changed how I set the cwd and added to sys.path, rglob might take a while
	- [x] no 2: also made it so that you dont have to add a file at the beginning anymore, that might change stuff, I check for fps in the shared dict which adds like 1ms EVERY frame, that adds up
	- [x] no 3: now in blit buffer I'll check for colorfmtval, that might also add things up and slow things down
	- [x] no 4: went from FastCVApp to fastcvapp to match everybody else
	- [x] no 5: changed all the examples to have a try/except block
	- [x] no 6: have try/except for import statements so it works in terminal: fastcvapp (1)\fastcvapp(2)\examples(3)\ pyinstaller (4) AND as a module (5) as pyinstaller module (6): 
- [x] **MAKE PYPI FIRST THEN CHECK AGAIN**
	- [x] poetry build
	- [x] in a fresh env, installed from wheel as per https://github.com/python-poetry/poetry/issues/76#issuecomment-385439995
	- [x] example worked!
- [x] check everything AGAIN, reminder that MAC compiles faster than windows if u have compile problems (but GAIM is on par with MAC)
- [x] REMEMBER TO BUILD WITH UPX ON WINDOWS
- [x] updated requirements.txt for windows and mac
- [x] BUILD IN A CLEAN ENV!
- [x] EXAMPLE USING FCVA AS MODULE: https://github.com/AccelQuasarDragon/fcvaproject
	- [x] on windows terminal it runs(from pyproject.toml)
		- [x] as pyinstaller with provided specfile it runs
	- [x] on mac terminal it runs (from pyproject.toml)
		- [x] as pyinstaller with provided specfile it runs
- [x] poetry installing from wheel:
	- [x] https://github.com/python-poetry/poetry/issues/76#issuecomment-385439995
- [x] removed rgb2rgba since it's more involved, need to keep going
- [x] check should be from fastcvapp (1) \fastcvapp (2) \ examples (3) (WINDOWS)
	- [x] fastcvapp (1) \
	- [x] fastcvapp (2) \ 
	- [x] examples (3) 
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc
	- [x] mediapipe
	- [x] sepiafilter (confirmed slow aug 24 23 only on 1080p, it's fine on mac tho..) moved to later issue; 
- [x] rebuild all the examples with PyInstaller (4) (WIN)
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] mediapipe
	- [x] sepiafilter
- [x] check should be from fastcvapp (1) \fastcvapp (2) \ examples (3) (MAC)
	- [x] fastcvapp (1) \
	- [x] fastcvapp (2) \ 
	- [x] examples (3) 
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc
	- [x] mediapipe
	- [x] sepiafilter (confirmed slow aug 24 23 only on 1080p, it's fine on mac tho..) moved to later issue; 
- [x] rebuild all the examples with PyInstaller (4) (MAC)
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] mediapipe
	- [x] sepiafilter
- [x] making a wheel for mac is pain, it's 15GB for some reason AKA build a wheel on an clean repo as well i guess #53
- [x] USING FCVA AS MODULE: run from terminal in fcvaproject (5) (WIN)
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc (no specfile)
	- [x] mediapipe
	- [x] sepiafilter
- [x] USING FCVA AS MODULE: rebuild all the examples with PyInstaller (6) (WIN) (skip the other exe)
	- [x] mediapipe
- [x] USING FCVA AS MODULE: run from terminal in fcvaproject (5) (MAC)
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc (no specfile)
	- [x] mediapipe
	- [x] sepiafilter
- [x] USING FCVA AS MODULE: rebuild all the examples with PyInstaller (6) (MAC) (skip the other exe)
	- [x] mediapipe
