### ISSUE TITLE
make sure it works... add base fcva folder to a new virtual environment and check if it works by just importing

### ISSUE THREAD

**Issue by AccelQuasarDragon** [AccelQuasarDragon/FastCVApp#41]
- [x] what i did:
- [x] lowercase the folder to match the other modules FastCVApp > fastcvapp
- [x] before from FCVAutils ... I did import fastcvapp (in lowercase)
- [x] NEW ERROR, nofiletest just crashed... that should not be the case
```
  current_sec = self.ids['vidsliderID'].value * (1/self.FCVAWidget_shared_metadata_dict["capfps"])       
  File "<string>", line 2, in __getitem__
  File "C:\Python39\lib\multiprocessing\managers.py", line 824, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'capfps'
```
- [x] also try and package that new project with pyinstaller (on windows/mac)
SO MANY THINGS FAIL
- [x] pyinstaller hooks fail, i have to manually add them
- [x] font is not moved properly
- [x] even updating image fails, so it repeats playing the same second over and over... (nah, it just fails on .flv.....) >#49
- [x] the last time a similiar bug happened it was because the media file was not loaded > self.fps was messed up > it had a bad spf and timer was messed up
- [x] solution IIRC
- [x] just add more try except blocks for pyinstaller to fail properly
- [x] made FastCVApp > fastcvapp to be similar to the other modules
- [x] solutions are to do import in try/except blocks as well
- [x] as for the specfile, make an issue to create a pyinstallerhook (I need the fontfile so it has to be a hook or smth) > #50
- [x] else just provide a working specfile
- [x] right now will TEST EVERYTHING on win/mac yet again, now on project AND ON EXAMPLE PROJECT..., added to #28, now will proceed to #30 since it's mostly done anyways once I confirm that i can make example mediapipe through pypi run through terminal and pyinstaller
